### ISSUE TITLE
Force atlas layout webworker cannot auto-stop

### ISSUE THREAD

**Issue by Kimi-Gao** [sim51/react-sigma-v2#15]
Hi,

https://sim51.github.io/react-sigma-v2/examples/complete.html

This example may crash my browser when clicking 
![image](https://user-images.githubusercontent.com/12554487/143559941-3a4bc216-72d6-45db-903d-d43548a70aef.png)
 to switch to force atlas layout.

The webworker will not auto-stop after 2000ms.

**Comment by sim51** [comment]
When you click on the play button, the FA2 is started, but there is not auto-stop on this.
The auto-stop is just for the first render.

What browser (with its version) are you using ?

**Comment by Kimi-Gao** [comment]
@sim51 Chrome macOS Version 96.0.4664.110 (Official Build) (x86_64)

If I don't click Stop manually, it will keep running and the computer will be buzzing. Now I use the synchronous layout algorithm, but move it into the web-worker manually to avoid ui blocking, and it can stop automatically. For the web-worker layout provided by graphology, I'm a little afraid to use it, maybe I'm using it in the wrong way.

**Comment by sim51** [comment]
Without an example that reproduce your issue, it will be hard for me to check what is going wrong. 

> Now I use the synchronous layout algorithm, but move it into the web-worker manually to avoid ui blocking, and it can stop automatically

This really what the FA2 worker do, but in FA2 there is not auto-stop feature. You can implement it by yourself with a settimeout and the `stop` method provider.
It's what I do here https://github.com/sim51/react-sigma-v2/blob/main/src/components/controls/layouts/WorkerLayoutControl.tsx#L89-L98

**Comment by Kimi-Gao** [comment]
@sim51 Got it,  I will try that with your code, thanks.
