### ISSUE TITLE
The JS file of the ESM module does not exist

### ISSUE THREAD

**Issue by ShirasawaSama** [sim51/react-sigma-v2#3]
![image](https://user-images.githubusercontent.com/17093811/125325482-90803e80-e373-11eb-84d2-f748bef6638f.png)

![image](https://user-images.githubusercontent.com/17093811/125325565-a4c43b80-e373-11eb-84ae-4dc46ebc1e34.png)

**Comment by sim51** [comment]
Thanks for the issue !
I just published the v0.0.5
