### ISSUE TITLE
Module not found: Can't resolve 'tslib'

### ISSUE THREAD

**Issue by mooijtech** [sim51/react-sigma-v2#7]
Hello,

I was getting the following error:
```
./node_modules/react-sigma-v2/lib/esm/SigmaContainer.js:4:0
Module not found: Can't resolve 'tslib'
```

I solved it by installing tslib: ```yarn add tslib``` 
Maybe it would be a good idea to add this to the documentation (dependencies)?

**Comment by sim51** [comment]
Weird ... it's the same issue on sandbox.
But I don't have this issue locally, neither on the CI.

You try this project locally, not on codesandbox  ?
What is the your OS ?

Thanks for the report

**Comment by mooijtech** [comment]
I'm using the project locally yes, my OS is Linux.

**Comment by sim51** [comment]
tslib has been added as a peer dependency
