### ISSUE TITLE
UsageGraphError: Graph.addNode: the "Jessica" node already exist in the graph.

### ISSUE THREAD

**Issue by mooijtech** [sim51/react-sigma-v2#9]
Hello again,

I'm having trouble getting ForceAtlas2 to work.

The following code works:
```js
import React from "react";
import {useSigma} from "react-sigma-v2";
import {random} from "graphology-layout"

export const NetworkGraph = ({nodes, links}) => {
    const sigma = useSigma();
    const graph = sigma.getGraph();

    graph.addNode("Jessica", { label: "Jessica", x: 0, y: 1, color: "#FF0", size: 10 });
    graph.addNode("Truman", { label: "Truman", x: 1, y: 0, color: "#00F", size: 10 });
    graph.addEdge("Jessica", "Truman", { color: "#CCC", size: 1 });

    random.assign(graph);

    return null;
}
```

But calling https://graphology.github.io/standard-library/layout-forceatlas2.html after the random assign doesn't:
```
forceAtlas2.assign(graph);
```
```
UsageGraphError: Graph.addNode: the "Jessica" node already exist in the graph.
```
Do you know what could be the issue?

**Comment by mooijtech** [comment]
It seems to work when I do a check for if the graph has the node:
```
  if (!graph.hasNode("Jessica")) {
        graph.addNode("Jessica", { label: "Jessica", x: 0, y: 1, color: "#FF0", size: 10 });
    }
```

Not sure why it's not removing the nodes on unmount.

**Comment by sim51** [comment]
The graph stays the same, event on unmount., it is stored on the SigmaContainer component.
If you want to reset the graph on unmount, you have to do it by yourself with an effect. 
FYI, graphology has some `merge` functions to add or update nodes/edges.

**Comment by mooijtech** [comment]
Thanks for the explanation, I appreciate your feedback as always.
I didn't know the state was persisted, I have added a useEffect when adding nodes and this works.

Thanks for this library.
